config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'breweries#index'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/beerlist', to:'beers#list'
  get '/brewerylist', to:'breweries#nglist'
  get '/ngbeerlist', to:'beers#nglist'

  post '/places', to:'places#search'
  
  delete '/signout', to: 'sessions#destroy'  

  resources :breweries do
    post 'toggle-activity', on: :member
  end

  resources :users do
    post 'toggle-activity', on: :member
  end

  resources :memberships, only: [:new, :create, :destroy] do
    post 'activate', on: :member
  end

  resources :beers
  resources :styles
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beer_clubs  
  resource :session, only: [:new, :create]
  resources :places, only: [:index, :show]
end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :beer_club
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:destroy, :activate]
  before_action :ensure_that_signed_in, only: [:new, :create, :destroy, :activate]

#  def index
#    @memberships = Membership.all
#  end

#  def show
#  end

  def new
    @membership = Membership.new
    @beer_clubs = clubs_not_joined
  end

#  def edit
#  end

  def create
    @membership = Membership.new(membership_params)
    @membership.confirmed = false
    @membership.user = current_user

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership.beer_club, notice: current_user.username + ', you have joined the club. Please wait for a club member to confirm your membership.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

#  def update
#    respond_to do |format|
#      if @membership.update(membership_params)
#        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
#        format.json { render :show, status: :ok, location: @membership }
#      else
#        format.html { render :edit }
#        format.json { render json: @membership.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  def destroy
    club = @membership.beer_club.name

    @membership.destroy if current_user == @membership.user or current_user.admin
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Membership in ' + club + ' ended.' }
      format.json { head :no_content }
    end
  end

  def activate
    current_user_membership = Membership.find_by(user_id: current_user.id, beer_club_id: @membership.beer_club.id)

    if current_user_membership and current_user_membership.confirmed
      @membership.update_attribute :confirmed, (true)
      redirect_to :back, notice: @membership.user.username + " became a confirmed club member."
    
    else
      redirect_to :back, notice: "You don't have the permission to do this."
    end
  end

  private
    def set_membership
      @membership = Membership.find(params[:id])
    end

    def clubs_not_joined
      @beer_clubs = BeerClub.all.reject { |club| current_user.beer_clubs.include?(club) }
    end

    def membership_params
      params.require(:membership).permit(:beer_club_id, :user_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beer_club_id %><br>
    <%= f.number_field :beer_club_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Beer club</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.beer_club_id %></td>
        <td><%= membership.user_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>Join a club</h1>

  <% if @beer_clubs.empty? %>
    <p>There are no clubs to join.</p>
  <% else %>
    <%= form_for(@membership) do |f| %>

      <%= f.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :to_s) %>
      <%= f.submit class: 'btn btn-primary' %>
  <% end %>
 
<% end %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beer club:</strong>
  <%= @membership.beer_club_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>