config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'breweries#index'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/beerlist', to:'beers#list'
  get '/brewerylist', to:'breweries#nglist'
  get '/ngbeerlist', to:'beers#nglist'

  post '/places', to:'places#search'
  
  delete '/signout', to: 'sessions#destroy'  

  resources :breweries do
    post 'toggle-activity', on: :member
  end

  resources :users do
    post 'toggle-activity', on: :member
  end

  resources :memberships, only: [:new, :create, :destroy] do
    post 'activate', on: :member
  end

  resources :beers
  resources :styles
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beer_clubs  
  resource :session, only: [:new, :create]
  resources :places, only: [:index, :show]
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user

  validates :name, length: { minimum: 1 }

  def to_s
    self.name + " - " + self.founded.to_s + " - " + self.city
  end

end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:destroy]

  def index
    @beer_clubs = BeerClub.all
  end

  def show
    set_membership
    @confirmed_members = confirmed_members
    @applied_members = applied_members
  end

  def new
    @beer_club = BeerClub.new
  end

  def edit
  end

  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        new_membership
        @membership.user = current_user
        @membership.confirmed = true
        @membership.save

        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#  def activate
#    set_membership #membership of current user
#
#    if @membership.confirmed
#      @membership = Membership.find_by(user_id: params[:id], beer_club_id: @beer_club.id)
#      @membership.update_attribute :confirmed, (true)
#
#      redirect_to :back, notice: @membership.user.username + " became a confirmed club member."
#    else
#      redirect_to :back, notice: "You don't have the permission to do this."
#    end
#  end

  private
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end

    def set_membership

      if current_user and current_user.beer_clubs.include?(@beer_club)
        @membership = Membership.find_by(user_id: current_user.id, beer_club_id: @beer_club.id)
     else
        new_membership
     end
   end

   def new_membership
     @membership = Membership.new
     @membership.beer_club = @beer_club
   end

   def confirmed_members
     members = []
     @beer_club.memberships.each do |ship|
       members << ship.user if ship.confirmed
     end
     members
   end

   def applied_members
     members = []
     @beer_club.memberships.each do |ship|
       members << ship.user if not ship.confirmed
     end
     members
   end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beer clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user %>
  <br>
  <%= link_to 'Create a new club', new_beer_club_path, class:'btn btn-primary' %>
<% end %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= @beer_club.name %> </h1>

<p>Founded <%= @beer_club.founded %> in <%= @beer_club.city %> </p>

<% if not @confirmed_members.empty? %>
  <h2>Members</h2>

  <ul>
    <% @confirmed_members.each do |member| %>
      <li>
        <%= link_to member.username, member %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if not @applied_members.empty? %>
  <h2>Outstanding applications</h2>

  <ul>
    <% @applied_members.each do |member| %>
      <li>
        <%= link_to member.username, member %>       
        
        <% @membership = current_user_membership_of(@beer_club) %>
        <% if @membership and @membership.confirmed %>

          <% @membership = membership_of(member, @beer_club) %>
          <%= link_to 'Confirm', activate_membership_path(@membership.id), method: :post, class:'btn btn-primary' %>

        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if current_user %>

  <% if not current_user.beer_clubs.include?(@beer_club) %>

    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value:"Join the club", class:'btn btn-primary' %>
    <% end %>
    
  <% else %>
    <%= form_for(@membership, method: "delete") do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value:"End the membership", class:'btn btn-danger' %>
    <% end %>

  <% end %>

  <br>
  <%= edit_and_destroy_buttons(@beer_club) %>
<% end %>