config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'breweries#index'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/beerlist', to:'beers#list'
  get '/brewerylist', to:'breweries#nglist'
  get '/ngbeerlist', to:'beers#nglist'

  post '/places', to:'places#search'
  
  delete '/signout', to: 'sessions#destroy'  

  resources :breweries do
    post 'toggle-activity', on: :member
  end

  resources :users do
    post 'toggle-activity', on: :member
  end

  resources :memberships, only: [:new, :create, :destroy] do
    post 'activate', on: :member
  end

  resources :beers
  resources :styles
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beer_clubs  
  resource :session, only: [:new, :create]
  resources :places, only: [:index, :show]
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1024,
                                 less_than_or_equal_to: ->(_){Time.now.year} }

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil,false] }

  def self.top(n)
    sorted_by_rating = Brewery.all.sort_by{ |b| -(b.average_rating||0) }

    i = 0
    arr = []
    
    sorted_by_rating.each do |brewery|
      if i < n
        arr << brewery
        i = i + 1
      end
    end
    
    arr
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy, :toggle_activity]
  before_action :ensure_that_signed_in, except: [:index, :show, :nglist]
  before_action :ensure_that_admin, only: [:destroy]
  before_action :clear_brewerylist_from_cache, only: [:create, :update, :destroy, :toggle_activity]
  before_action :skip_if_cached, only: [:index]

  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    order = params[:order] || 'name'

    if order == 'name'
      @active_breweries = @active_breweries.sort_by{ |b| b.name }
      @retired_breweries = @retired_breweries.sort_by{ |b| b.name }
      
      if session[:breweries_order] == 'name' # viimeksi kun käytiin sivulla, järjestettiin panimot nimen mukaan
        if params[:order] # metodiin tultiin käymällä klikkaamassa breweries -sivulla 'Name' kenttää (eikä jostain muulta sivulta)
          reverse_order
        end
      else
        update_breweries_order(order)
      end

    elsif order == 'year'
      @active_breweries = @active_breweries.sort_by{ |b| b.year }
      @retired_breweries = @retired_breweries.sort_by{ |b| b.year }

      if session[:breweries_order] == 'year'      
        reverse_order
      else
        update_breweries_order(order)
      end
    end
  end

 
  def show
  end


  def new
    @brewery = Brewery.new
  end

 
  def edit
  end

  def nglist
  end

  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    @brewery.update_attribute :active, (not @brewery.active)

    new_status = @brewery.active? ? "active" : "retired"
    redirect_to :back, notice:"Brewery activity status changed to #{new_status}."
  end

  def clear_brewerylist_from_cache
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
  end

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerylist-#{@order}"  )
  end

  private
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    def update_breweries_order(order)
      session[:breweries_order] = order
    end

    def reverse_order
      session[:breweries_order] = nil
      @active_breweries.reverse!
      @retired_breweries.reverse!
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
    <th><%= link_to 'Name', breweries_path(order:"name") %></th>
    <th><%= link_to 'Year', breweries_path(order:"year") %></th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<div style="border-style: solid;">
  brewerylist-name: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-name' ) %>
  <br>
  brewerylist-year: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-year' ) %>
  <br>
  current: <%= "brewerylist-#{@order}" %>
</div>

<h1>Listing Breweries</h1>

<% cache "brewerylist-#{@order}", skip_digest: true do %>

<h2>Active</h2>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= render 'list', breweries: @retired_breweries %>

<% end %>

<% if current_user %>
  <br>
  <%= link_to 'New Brewery', new_brewery_path, class:'btn btn-primary' %>
<% end %>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/nglist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular.min.js"></script>

<script>
  var myApp = angular.module('myApp', []);

  myApp.controller("BreweriesController", function ($scope, $http) {
    $http.get('breweries.json').success( function(data, status, headers, config) {
      $scope.breweries = data;
    });

    $scope.order = 'name';

    $scope.sort_by = function (order){
      $scope.order = order;
      console.log(order);
    }

    $scope.searchText = '';
  });
</script>

<h2>Breweries</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">name</a> </th>
    <th> <a ng-click="sort_by('year')">year</a> </th>
    </thead>
    
    <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
    </tr>
  </table>

</div>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @brewery do %>

<h2><%= @brewery.name %> </h2>

<% if not @brewery.active %>
  <span class="label label-info">retired</span>
  <br>
<% end %>

<p><em> Established in <%= @brewery.year %> </em></p>

<p>Number of beers: <%= @brewery.beers.count %></p>
  
<ul>
  <% @brewery.beers.each do |beer| %>
    <li> <%= link_to beer.name, beer %> </li>
  <% end %>
</ul>

<% if not @brewery.ratings.empty? %>
  <p>Has <%= pluralize(@brewery.ratings.count, 'rating') %>, average <%= round(@brewery.average_rating) %> </p>
<% end %>

<% end %>

<%= edit_and_destroy_buttons(@brewery) %>

<% if current_user %>
  <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
<% end %>